load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

os_header_bfile_content = """cc_library(name = "os", hdrs = ["os.h"], include_prefix = "os_header", strip_include_prefix = "/", visibility = ["//visibility:public"])"""

http_archive(
  name = "os_header_ubuntu_18.04",
  urls = ["https://github.com/thekyz/snippets/raw/master/os_based_http_dep/tar_gz/ubuntu_18.04.tar.gz"],
  sha256 = "1564e6813534f5af0ac1cc325b7dd697caeb229fbc1b492f6d44010ef0e60b81",
  build_file_content = os_header_bfile_content,
)

http_archive(
  name = "os_header_ubuntu_20.04",
  urls = ["https://github.com/thekyz/snippets/raw/master/os_based_http_dep/tar_gz/ubuntu_20.04.tar.gz"],
  # sha256 = "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855",
  build_file_content = os_header_bfile_content,
)
