py_binary(
    name = "hello_base",
    srcs = [
        "hello_base.py",
    ],
    visibility = ["//visibility:public"],
)

py_binary(
    name = "hello_gather",
    srcs = [
        "hello_gather.py",
    ],
    visibility = ["//visibility:public"],
)
