load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

# Package rules
http_archive(
    name = "rules_pkg",
    url = "https://github.com/bazelbuild/rules_pkg/releases/download/0.2.4/rules_pkg-0.2.4.tar.gz",
    sha256 = "4ba8f4ab0ff85f2484287ab06c0d871dcb31cc54d439457d28fd4ae14b18450a",
)
load("@rules_pkg//:deps.bzl", "rules_pkg_dependencies")
rules_pkg_dependencies()

# Extra skylib stuff
#load("@bazel_tools//tools/build_defs/repo:utils.bzl", "maybe")
#maybe(
#    http_archive,
#    name = "bazel_skylib",
#    url = "https://github.com/bazelbuild/bazel-skylib/releases/download/0.9.0/bazel_skylib-0.9.0.tar.gz",
#    sha256 = "1dde365491125a3db70731e25658dfdd3bc5dbdfd11b840b3e987ecf043c7ca0",
#)
#load("@bazel_skylib//:workspace.bzl", "bazel_skylib_workspace")
#bazel_skylib_workspace()

# Toolchains
register_toolchains(
    "//toolchains/ppc:ppc_buildroot_toolchain",
    "//toolchains/x86:x86_buildroot_toolchain",
)
