load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

# Package rules
http_archive(
    name = "rules_pkg",
    url = "https://github.com/bazelbuild/rules_pkg/releases/download/0.2.5/rules_pkg-0.2.5.tar.gz",
    sha256 = "352c090cc3d3f9a6b4e676cf42a6047c16824959b438895a76c2989c6d7c246a",
)
load("@rules_pkg//:deps.bzl", "rules_pkg_dependencies")
rules_pkg_dependencies()

# Extra skylib stuff
#load("@bazel_tools//tools/build_defs/repo:utils.bzl", "maybe")
#maybe(
#    http_archive,
#    name = "bazel_skylib",
#    url = "https://github.com/bazelbuild/bazel-skylib/releases/download/0.9.0/bazel_skylib-0.9.0.tar.gz",
#    sha256 = "1dde365491125a3db70731e25658dfdd3bc5dbdfd11b840b3e987ecf043c7ca0",
#)
#load("@bazel_skylib//:workspace.bzl", "bazel_skylib_workspace")
#bazel_skylib_workspace()

# Toolchains
register_toolchains(
    "//toolchains/gcc-arm-none-eabi:gcc_arm_none_eabi_toolchain",
    "//toolchains/mac:gcc_mac_toolchain",
)
