constraint_setting(name = "cpu")

constraint_value(
    name = "arm",
    constraint_setting = ":cpu",
    visibility = ["//visibility:public"],
)

constraint_value(
    name = "mac",
    constraint_setting = ":cpu",
    visibility = ["//visibility:public"],
)
