constraint_setting(name = "cpu")

constraint_value(
    name = "ppc",
    constraint_setting = ":cpu",
    visibility = ["//visibility:public"],
)

constraint_value(
    name = "x86",
    constraint_setting = ":cpu",
    visibility = ["//visibility:public"],
)
