load("//:defs.bzl", "library_transition_rule", "binary_transition_rule", "import_transition_rule", "cc_library", "cc_binary", "cc_import")

cc_import(
    name = "protobuf",
    shared_library = "libprotobuf.so",
    visibility = ["//visibility:public"],
)
