constraint_setting(name = "os")

constraint_value(
    name = "linux",
    constraint_setting = ":os",
    visibility = ["//visibility:public"],
)
constraint_value(
    name = "mac",
    constraint_setting = ":os",
    visibility = ["//visibility:public"],
)
